/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ncsu.monopoly.gui;

import edu.ncsu.monopoly.GameMaster;
import edu.ncsu.monopoly.Player;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Federico
 */
public class CreateNewPlayer extends javax.swing.JFrame {

    private File picture;

    /**
     * Creates new form NuevoJugador
     */
    public CreateNewPlayer() {
        initComponents();
        picture = new File(("/Imagenes/Perfil blanco.jpg"));
        colorChoice.addItem("RED");
        colorChoice.addItem("BLUE");
        colorChoice.addItem("GREEN");
        colorChoice.addItem("PINK");
        colorChoice.addItem("GRAY");
        colorChoice.addItem("ORANGE");
        colorChoice.addItem("YELLOW");
        colorChoice.addItem("WHITE");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        colorChoice = new java.awt.Choice();
        jButton1 = new javax.swing.JButton();
        exitBtt = new javax.swing.JButton();
        profilePhoto = new javax.swing.JLabel();
        createBtt = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 300));
        getContentPane().setLayout(null);
        getContentPane().add(nameText);
        nameText.setBounds(350, 50, 155, 22);

        jLabel1.setText("Player name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 50, 76, 20);

        jLabel3.setText("Color:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 80, 40, 16);
        getContentPane().add(colorChoice);
        colorChoice.setBounds(350, 80, 150, 20);

        jButton1.setText("New profile photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(345, 120, 160, 25);

        exitBtt.setText("Cancel");
        exitBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBttActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtt);
        exitBtt.setBounds(280, 220, 110, 25);

        profilePhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profilePhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Perfil blanco.jpg"))); // NOI18N
        profilePhoto.setLabelFor(this);
        profilePhoto.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        profilePhoto.setMaximumSize(new java.awt.Dimension(240, 240));
        profilePhoto.setMinimumSize(new java.awt.Dimension(240, 240));
        profilePhoto.setPreferredSize(new java.awt.Dimension(240, 240));
        getContentPane().add(profilePhoto);
        profilePhoto.setBounds(10, 10, 240, 240);

        createBtt.setText("Create");
        createBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBttActionPerformed(evt);
            }
        });
        getContentPane().add(createBtt);
        createBtt.setBounds(400, 220, 110, 25);

        jPanel1.setMinimumSize(new java.awt.Dimension(520, 260));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 520, 260);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int resultado;

        PictureChooser windowPC = new PictureChooser();

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG", "jpg", "png");

        windowPC.selectPicture.setFileFilter(filtro);

        resultado = windowPC.selectPicture.showOpenDialog(null);

        if (JFileChooser.APPROVE_OPTION == resultado) {

            picture = windowPC.selectPicture.getSelectedFile();

            try {

                ImageIcon icon = new ImageIcon(picture.toString());

                Icon icono = new ImageIcon(icon.getImage().getScaledInstance(profilePhoto.getWidth(), profilePhoto.getHeight(), Image.SCALE_DEFAULT));

                profilePhoto.setIcon(icono);

            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, "Error abriendo la imagen " + ex);

            }

        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void exitBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBttActionPerformed
        // TODO add your handling code here:
        new GameOptions().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_exitBttActionPerformed

    private void createBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBttActionPerformed

        GameMaster master = GameMaster.instance();
        boolean unique = true;

        for (int i = 0; i < master.getRegistredPlayers().size(); i++) {

            if (master.getRegistredPlayers().get(i).getName().equals(nameText.getText())) {
                unique = false;
            }
        }

        if (unique) {
            Player player = new Player();
            player.setName(nameText.getText());
            player.setPerfil(picture);
            player.setGamesPlayed(0);
            player.setGamesWon(0);

            switch (colorChoice.getSelectedItem()) {
                case "RED":
                    player.setColor(Color.RED);
                    break;
                case "BLUE":
                    player.setColor(Color.BLUE);
                    break;
                case "GREEN":
                    player.setColor(Color.GREEN);
                    break;
                case "PINK":
                    player.setColor(Color.PINK);
                    break;
                case "GRAY":
                    player.setColor(Color.GRAY);
                    break;
                case "ORANGE":
                    player.setColor(Color.ORANGE);
                    break;
                case "YELLOW":
                    player.setColor(Color.YELLOW);
                    break;
                case "WHITE":
                    player.setColor(Color.WHITE);
                    break;
                default:
                    player.setColor(Color.GREEN);
                    break;
            }

            master.newPlayer(player);
            new GameOptions().setVisible(true);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Error: The name entered is already being used.");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_createBttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateNewPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateNewPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateNewPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateNewPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateNewPlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice colorChoice;
    private javax.swing.JButton createBtt;
    private javax.swing.JButton exitBtt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel profilePhoto;
    // End of variables declaration//GEN-END:variables
}
